steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['build', '-t', 'gcr.io/$PROJECT_ID/fitsync-main-api:$COMMIT_SHA', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/fitsync-main-api:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'fitsync-main-api'
      - '--allow-unauthenticated'
      - '--image'
      - 'gcr.io/$PROJECT_ID/fitsync-main-api:$COMMIT_SHA'
      - '--region'
      - 'asia-southeast2'
      - '--service-account'
      - 'main-api-cloud-run@fitsync-406408.iam.gserviceaccount.com'
      - '--add-cloudsql-instances'
      - 'fitsync-406408:us-central1:main-mysql'
      - '--port'
      - '8080'
      - '--labels'
      - 'environment=development'
      - '--env-vars-file'
      - 'env.dev.yaml'
      - '--set-secrets'
      - 'API_KEY=fitsync-main-api-API_KEY:latest'
      - '--set-secrets'
      - 'DB_PASSWORD=fitsync-main-api-DB_PASSWORD:latest'
      - '--set-secrets'
      - 'ACCESS_TOKEN_PRIVATE_KEY=fitsync-main-api-ACCESS_TOKEN_PRIVATE_KEY:latest'
      - '--set-secrets'
      - 'REFRESH_TOKEN_PRIVATE_KEY=fitsync-main-api-REFRESH_TOKEN_PRIVATE_KEY:latest'
      - '--set-secrets'
      - 'EMAIL_TRANSPORTER_PASSWORD=fitsync-main-api-EMAIL_TRANSPORTER_PASSWORD:latest'
      - '--set-secrets'
      - 'TYPESENSE_API_KEY=firestore-typesense-search-TYPESENSE_API_KEY:latest'
images:
  - 'gcr.io/$PROJECT_ID/fitsync-main-api:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
